In [5]:
# Imports
import numpy as np

import torch

In [1]:
!pip list

Package                       Version
----------------------------- --------------
aniso8601                     9.0.1
annotated-types               0.5.0
ansi2html                     1.8.0
anyio                         3.7.1
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
asttokens                     2.2.1
async-lru                     2.0.3
attrs                         23.1.0
autovizwidget                 0.20.5
awscli                        1.29.57
Babel                         2.12.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.5
beautifulsoup4                4.12.2
bleach                        6.0.0
blinker                       1.6.2
bokeh                         3.2.0
boto3                         1.28.57
botocore                      1.31.57
brotlipy                      0.7.0
captum                        0.6.0
certifi                       2023.5.7
cffi                          1.15.1
c

In [2]:
print(10+9)

19


In [3]:
array = [1, 2, 3, 4, 5]
for x in array:
    print(x)

1
2
3
4
5


In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.75451363, 0.67858889, 0.92800889, 0.36767635],
       [0.72106558, 0.07847357, 0.81015103, 0.88420425],
       [0.36424483, 0.60904593, 0.32420302, 0.53130513]])

In [8]:
tensor = torch.randn(3,4)
tensor

tensor([[ 0.4717,  0.1492, -0.8408, -0.0052],
        [ 1.1175, -1.1857,  0.2676, -2.1607],
        [ 0.2193, -2.3990,  0.3523,  0.9011]])

In [9]:
tensor2 = torch.randn(3,3,3)
tensor2

tensor([[[-0.3127,  0.4009, -0.2273],
         [ 0.3512, -0.1375,  0.5317],
         [ 0.4634,  1.9093, -2.3388]],

        [[-0.2794,  2.1255,  1.6184],
         [-0.7120, -0.0192,  1.0723],
         [-1.5357, -0.2943, -0.1448]],

        [[ 1.5144,  2.6804, -0.4837],
         [ 0.3521,  2.2689,  2.9724],
         [ 0.4969,  0.8842,  0.9685]]])

In [12]:
tensor_4d = torch.randn(2,2,3,4)
tensor_4d

tensor([[[[ 1.3266, -0.3601, -1.1422,  0.0149],
          [-0.8762, -0.2616, -0.2876,  0.1883],
          [-1.0328, -1.4551,  0.0305,  2.2737]],

         [[-0.3208,  1.4371, -0.5297,  0.3334],
          [-1.1867, -0.0660,  0.0941,  1.3703],
          [-0.3564,  0.9125,  1.2219,  0.7449]]],


        [[[-0.0832,  1.5174,  2.3801, -1.1844],
          [ 0.7154,  1.0968,  0.3924, -0.7341],
          [ 1.0092,  1.2401, -0.8148,  0.0200]],

         [[-1.9072,  1.2414,  1.6349,  1.1941],
          [ 0.0583,  0.4339,  1.1565,  0.4238],
          [ 0.3498,  0.4551, -1.4253, -1.3112]]]])

In [13]:
## Tensor to np array
new_tensor = torch.tensor(np1)
new_tensor

tensor([[0.7545, 0.6786, 0.9280, 0.3677],
        [0.7211, 0.0785, 0.8102, 0.8842],
        [0.3642, 0.6090, 0.3242, 0.5313]], dtype=torch.float64)