In [2]:
# Imports
import numpy as np

import torch

In [3]:
!pip list

Package                       Version
----------------------------- -----------------
accelerate                    0.19.0
apex                          0.1
asttokens                     2.2.1
attrs                         22.2.0
awscli                        1.27.132
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
bcrypt                        4.0.1
blis                          0.7.9
bokeh                         3.1.1
boto3                         1.26.132
botocore                      1.29.132
brotlipy                      0.7.0
cached-property               1.5.2
catalogue                     2.0.8
certifi                       2023.5.7
cffi                          1.15.1
charset-normalizer            3.1.0
click                         8.1.3
cloudpickle                   2.2.1
cmake                         3.26.3
colorama                      0.4.4
comm                          0.1.3
commonmark                    0.9.1
conda                         23.1.0

In [4]:
print(10+9)

19


In [5]:
array = [1, 2, 3, 4, 5]
for x in array:
    print(x)

1
2
3
4
5


In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.18614194, 0.41247806, 0.57696424, 0.41423548],
       [0.0714406 , 0.75530898, 0.11636317, 0.24420921],
       [0.5618825 , 0.10528516, 0.28412691, 0.29503223]])

In [7]:
tensor = torch.randn(3,4)
tensor

tensor([[ 0.2109,  0.0659, -0.7484,  0.5497],
        [-2.5362, -0.4813,  1.1317, -0.9399],
        [ 1.2304, -0.7093,  0.1974,  0.2166]])

In [8]:
tensor2 = torch.randn(3,3,3)
tensor2

tensor([[[-0.4517, -0.1662,  1.5339],
         [ 0.7881, -1.6814,  0.3990],
         [-1.4395, -0.8763, -0.3223]],

        [[-0.7574,  1.4149, -0.3431],
         [-0.0038,  1.2702, -2.2689],
         [ 0.7266,  1.4402, -1.9230]],

        [[-2.1525,  1.7584,  0.8026],
         [ 0.8081,  0.6686, -0.6392],
         [ 0.1558,  0.5599,  0.3573]]])

In [9]:
tensor_4d = torch.randn(2,2,3,4)
tensor_4d

tensor([[[[ 1.0384, -0.8245, -1.0357, -0.6376],
          [ 0.4788,  1.4461, -1.9388, -2.2681],
          [ 1.9139,  0.6232, -1.3186, -0.3668]],

         [[ 0.0814, -2.0384, -0.0164,  1.5552],
          [-0.3366,  0.1558,  0.1634,  0.0748],
          [ 0.1774, -0.4104,  1.1045, -0.6650]]],


        [[[-0.4685, -0.1852, -0.1591, -0.0870],
          [-0.8467,  0.3249,  0.7376, -0.9643],
          [-0.8953, -0.2422,  0.3924,  0.7796]],

         [[ 0.9754,  1.0364,  1.0395, -1.7534],
          [ 1.3289, -0.7180,  1.7098, -0.0557],
          [ 1.5068, -0.0550,  1.0715,  0.5306]]]])

In [10]:
## Tensor to np array
new_tensor = torch.tensor(np1)
new_tensor

tensor([[0.1861, 0.4125, 0.5770, 0.4142],
        [0.0714, 0.7553, 0.1164, 0.2442],
        [0.5619, 0.1053, 0.2841, 0.2950]], dtype=torch.float64)

In [11]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([4,2,5,6])
tensor_a + tensor_b

tensor([ 5,  4,  8, 10])

In [12]:
tensor_a * tensor_b

tensor([ 4,  4, 15, 24])

In [13]:
tensor_a ** tensor_b

tensor([   1,    4,  243, 4096])

In [14]:
tensor_a - tensor_b

tensor([-3,  0, -2, -2])